//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaRendererApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormulaRendererApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTitle {
            get {
                return ResourceManager.GetString("CancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is back! Go ahead..
        /// </summary>
        public static string ConnectionBack {
            get {
                return ResourceManager.GetString("ConnectionBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your connection..
        /// </summary>
        public static string ConnectionLostMessage {
            get {
                return ResourceManager.GetString("ConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost.
        /// </summary>
        public static string ConnectionLostTitle {
            get {
                return ResourceManager.GetString("ConnectionLostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a formula first..
        /// </summary>
        public static string EmptyFormulaMessage {
            get {
                return ResourceManager.GetString("EmptyFormulaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Formula.
        /// </summary>
        public static string EmptyFormulaTitle {
            get {
                return ResourceManager.GetString("EmptyFormulaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not respond. Try again later..
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server problem.
        /// </summary>
        public static string InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your connection..
        /// </summary>
        public static string LimitedConnectionMessage {
            get {
                return ResourceManager.GetString("LimitedConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited connection.
        /// </summary>
        public static string LimitedConnectionTitle {
            get {
                return ResourceManager.GetString("LimitedConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without storage permission the image cannot be stored. Please allow permissions here or in the settings..
        /// </summary>
        public static string PermissionNotGrantedMessage {
            get {
                return ResourceManager.GetString("PermissionNotGrantedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission needed.
        /// </summary>
        public static string PermissionNotGrantedTitle {
            get {
                return ResourceManager.GetString("PermissionNotGrantedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula image.
        /// </summary>
        public static string SharingTitle {
            get {
                return ResourceManager.GetString("SharingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again..
        /// </summary>
        public static string SomethingWentWrongMessage {
            get {
                return ResourceManager.GetString("SomethingWentWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully stored in .
        /// </summary>
        public static string SuccessfulFileStorage {
            get {
                return ResourceManager.GetString("SuccessfulFileStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here it is!.
        /// </summary>
        public static string SuccessfulRender {
            get {
                return ResourceManager.GetString("SuccessfulRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared successfully!.
        /// </summary>
        public static string SuccessfulShare {
            get {
                return ResourceManager.GetString("SuccessfulShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Renderer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that the formula is correct..
        /// </summary>
        public static string WrongFormulaMessage {
            get {
                return ResourceManager.GetString("WrongFormulaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string WrongFormulaTitle {
            get {
                return ResourceManager.GetString("WrongFormulaTitle", resourceCulture);
            }
        }
    }
}
